//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 09:29:41 AM CEST 
//


package com.opensimulationplatform.systemstructure.xml.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.opensimulationplatform.cseconfig.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.opensimulationplatform.cseconfig.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VariableConnections }
     * 
     */
    public VariableConnections createVariableConnections() {
        return new VariableConnections();
    }

    /**
     * Create an instance of {@link VariableConnections.SumConnection }
     * 
     */
    public VariableConnections.SumConnection createVariableConnectionsSumConnection() {
        return new VariableConnections.SumConnection();
    }

    /**
     * Create an instance of {@link BondConnections }
     * 
     */
    public BondConnections createBondConnections() {
        return new BondConnections();
    }

    /**
     * Create an instance of {@link PlugSocketConnections }
     * 
     */
    public PlugSocketConnections createPlugSocketConnections() {
        return new PlugSocketConnections();
    }

    /**
     * Create an instance of {@link Simulators }
     * 
     */
    public Simulators createSimulators() {
        return new Simulators();
    }

    /**
     * Create an instance of {@link Simulators.Simulator }
     * 
     */
    public Simulators.Simulator createSimulatorsSimulator() {
        return new Simulators.Simulator();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues }
     * 
     */
    public Simulators.Simulator.InitialValues createSimulatorsSimulatorInitialValues() {
        return new Simulators.Simulator.InitialValues();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues.InitialValue }
     * 
     */
    public Simulators.Simulator.InitialValues.InitialValue createSimulatorsSimulatorInitialValuesInitialValue() {
        return new Simulators.Simulator.InitialValues.InitialValue();
    }

    /**
     * Create an instance of {@link OspSystemStructure }
     * 
     */
    public OspSystemStructure createOspSystemStructure() {
        return new OspSystemStructure();
    }

    /**
     * Create an instance of {@link ConnectionEndpoint }
     * 
     */
    public ConnectionEndpoint createConnectionEndpoint() {
        return new ConnectionEndpoint();
    }

    /**
     * Create an instance of {@link VariableConnections.ScalarConnection }
     * 
     */
    public VariableConnections.ScalarConnection createVariableConnectionsScalarConnection() {
        return new VariableConnections.ScalarConnection();
    }

    /**
     * Create an instance of {@link VariableConnections.SumConnection.Sources }
     * 
     */
    public VariableConnections.SumConnection.Sources createVariableConnectionsSumConnectionSources() {
        return new VariableConnections.SumConnection.Sources();
    }

    /**
     * Create an instance of {@link BondConnections.BondConnection }
     * 
     */
    public BondConnections.BondConnection createBondConnectionsBondConnection() {
        return new BondConnections.BondConnection();
    }

    /**
     * Create an instance of {@link PlugSocketConnections.PlugSocketConnection }
     * 
     */
    public PlugSocketConnections.PlugSocketConnection createPlugSocketConnectionsPlugSocketConnection() {
        return new PlugSocketConnections.PlugSocketConnection();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues.InitialValue.Real }
     * 
     */
    public Simulators.Simulator.InitialValues.InitialValue.Real createSimulatorsSimulatorInitialValuesInitialValueReal() {
        return new Simulators.Simulator.InitialValues.InitialValue.Real();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues.InitialValue.Integer }
     * 
     */
    public Simulators.Simulator.InitialValues.InitialValue.Integer createSimulatorsSimulatorInitialValuesInitialValueInteger() {
        return new Simulators.Simulator.InitialValues.InitialValue.Integer();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues.InitialValue.Boolean }
     * 
     */
    public Simulators.Simulator.InitialValues.InitialValue.Boolean createSimulatorsSimulatorInitialValuesInitialValueBoolean() {
        return new Simulators.Simulator.InitialValues.InitialValue.Boolean();
    }

    /**
     * Create an instance of {@link Simulators.Simulator.InitialValues.InitialValue.String }
     * 
     */
    public Simulators.Simulator.InitialValues.InitialValue.String createSimulatorsSimulatorInitialValuesInitialValueString() {
        return new Simulators.Simulator.InitialValues.InitialValue.String();
    }

}
