//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 09:29:41 AM CEST 
//


package com.opensimulationplatform.systemstructure.xml.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BaseStepSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Simulators" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}simulators"/>
 *         &lt;element name="PlugSocketConnections" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}plugSocketConnections"/>
 *         &lt;element name="BondConnections" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}bondConnections"/>
 *         &lt;element name="VariableConnections" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}variableConnections"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startTime",
    "baseStepSize",
    "algorithm",
    "simulators",
    "plugSocketConnections",
    "bondConnections",
    "variableConnections"
})
@XmlRootElement(name = "OspSystemStructure")
public class OspSystemStructure {

    @XmlElement(name = "StartTime", defaultValue = "0.0")
    protected Double startTime;
    @XmlElement(name = "BaseStepSize")
    protected Double baseStepSize;
    @XmlElement(name = "Algorithm", defaultValue = "fixedStep")
    protected String algorithm;
    @XmlElement(name = "Simulators", required = true)
    protected Simulators simulators;
    @XmlElement(name = "PlugSocketConnections", required = true)
    protected PlugSocketConnections plugSocketConnections;
    @XmlElement(name = "BondConnections", required = true)
    protected BondConnections bondConnections;
    @XmlElement(name = "VariableConnections", required = true)
    protected VariableConnections variableConnections;

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStartTime(Double value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the baseStepSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBaseStepSize() {
        return baseStepSize;
    }

    /**
     * Sets the value of the baseStepSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBaseStepSize(Double value) {
        this.baseStepSize = value;
    }

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithm(String value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the simulators property.
     * 
     * @return
     *     possible object is
     *     {@link Simulators }
     *     
     */
    public Simulators getSimulators() {
        return simulators;
    }

    /**
     * Sets the value of the simulators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simulators }
     *     
     */
    public void setSimulators(Simulators value) {
        this.simulators = value;
    }

    /**
     * Gets the value of the plugSocketConnections property.
     * 
     * @return
     *     possible object is
     *     {@link PlugSocketConnections }
     *     
     */
    public PlugSocketConnections getPlugSocketConnections() {
        return plugSocketConnections;
    }

    /**
     * Sets the value of the plugSocketConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlugSocketConnections }
     *     
     */
    public void setPlugSocketConnections(PlugSocketConnections value) {
        this.plugSocketConnections = value;
    }

    /**
     * Gets the value of the bondConnections property.
     * 
     * @return
     *     possible object is
     *     {@link BondConnections }
     *     
     */
    public BondConnections getBondConnections() {
        return bondConnections;
    }

    /**
     * Sets the value of the bondConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BondConnections }
     *     
     */
    public void setBondConnections(BondConnections value) {
        this.bondConnections = value;
    }

    /**
     * Gets the value of the variableConnections property.
     * 
     * @return
     *     possible object is
     *     {@link VariableConnections }
     *     
     */
    public VariableConnections getVariableConnections() {
        return variableConnections;
    }

    /**
     * Sets the value of the variableConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableConnections }
     *     
     */
    public void setVariableConnections(VariableConnections value) {
        this.variableConnections = value;
    }

}
