//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 09:29:41 AM CEST 
//


package com.opensimulationplatform.systemstructure.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for variableConnections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variableConnections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScalarConnection" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
 *                   &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SumConnection" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Sources">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variableConnections", propOrder = {
    "scalarConnection",
    "sumConnection"
})
public class VariableConnections {

    @XmlElement(name = "ScalarConnection")
    protected List<VariableConnections.ScalarConnection> scalarConnection;
    @XmlElement(name = "SumConnection")
    protected List<VariableConnections.SumConnection> sumConnection;

    /**
     * Gets the value of the scalarConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scalarConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScalarConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariableConnections.ScalarConnection }
     * 
     * 
     */
    public List<VariableConnections.ScalarConnection> getScalarConnection() {
        if (scalarConnection == null) {
            scalarConnection = new ArrayList<VariableConnections.ScalarConnection>();
        }
        return this.scalarConnection;
    }

    /**
     * Gets the value of the sumConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sumConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSumConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariableConnections.SumConnection }
     * 
     * 
     */
    public List<VariableConnections.SumConnection> getSumConnection() {
        if (sumConnection == null) {
            sumConnection = new ArrayList<VariableConnections.SumConnection>();
        }
        return this.sumConnection;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
     *         &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source",
        "target"
    })
    public static class ScalarConnection {

        @XmlElement(name = "Source", required = true)
        protected ConnectionEndpoint source;
        @XmlElement(name = "Target", required = true)
        protected ConnectionEndpoint target;

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public ConnectionEndpoint getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public void setSource(ConnectionEndpoint value) {
            this.source = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public ConnectionEndpoint getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public void setTarget(ConnectionEndpoint value) {
            this.target = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Sources">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sources",
        "target"
    })
    public static class SumConnection {

        @XmlElement(name = "Sources", required = true)
        protected VariableConnections.SumConnection.Sources sources;
        @XmlElement(name = "Target", required = true)
        protected ConnectionEndpoint target;

        /**
         * Gets the value of the sources property.
         * 
         * @return
         *     possible object is
         *     {@link VariableConnections.SumConnection.Sources }
         *     
         */
        public VariableConnections.SumConnection.Sources getSources() {
            return sources;
        }

        /**
         * Sets the value of the sources property.
         * 
         * @param value
         *     allowed object is
         *     {@link VariableConnections.SumConnection.Sources }
         *     
         */
        public void setSources(VariableConnections.SumConnection.Sources value) {
            this.sources = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public ConnectionEndpoint getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public void setTarget(ConnectionEndpoint value) {
            this.target = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source"
        })
        public static class Sources {

            @XmlElement(name = "Source", required = true)
            protected List<ConnectionEndpoint> source;

            /**
             * Gets the value of the source property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the source property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSource().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ConnectionEndpoint }
             * 
             * 
             */
            public List<ConnectionEndpoint> getSource() {
                if (source == null) {
                    source = new ArrayList<ConnectionEndpoint>();
                }
                return this.source;
            }

        }

    }

}
