//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 09:29:41 AM CEST 
//


package com.opensimulationplatform.cseconfig.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for plugSocketConnections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="plugSocketConnections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PlugSocketConnection" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
 *                   &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "plugSocketConnections", propOrder = {
    "plugSocketConnection"
})
public class PlugSocketConnections {

    @XmlElement(name = "PlugSocketConnection")
    protected List<PlugSocketConnections.PlugSocketConnection> plugSocketConnection;

    /**
     * Gets the value of the plugSocketConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plugSocketConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlugSocketConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlugSocketConnections.PlugSocketConnection }
     * 
     * 
     */
    public List<PlugSocketConnections.PlugSocketConnection> getPlugSocketConnection() {
        if (plugSocketConnection == null) {
            plugSocketConnection = new ArrayList<PlugSocketConnections.PlugSocketConnection>();
        }
        return this.plugSocketConnection;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Source" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
     *         &lt;element name="Target" type="{http://opensimulationplatform.com/MSMI/OSPSystemStructure}connectionEndpoint"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source",
        "target"
    })
    public static class PlugSocketConnection {

        @XmlElement(name = "Source", required = true)
        protected ConnectionEndpoint source;
        @XmlElement(name = "Target", required = true)
        protected ConnectionEndpoint target;

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public ConnectionEndpoint getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public void setSource(ConnectionEndpoint value) {
            this.source = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public ConnectionEndpoint getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConnectionEndpoint }
         *     
         */
        public void setTarget(ConnectionEndpoint value) {
            this.target = value;
        }

    }

}
