//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 12:28:02 PM CEST 
//


package com.opensimulationplatform.modeldescription.xml.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.opensimulationplatform.modeldescription.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.opensimulationplatform.modeldescription.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link Bonds }
     * 
     */
    public Bonds createBonds() {
        return new Bonds();
    }

    /**
     * Create an instance of {@link Bonds.Bond }
     * 
     */
    public Bonds.Bond createBondsBond() {
        return new Bonds.Bond();
    }

    /**
     * Create an instance of {@link Bonds.Bond.BondSockets }
     * 
     */
    public Bonds.Bond.BondSockets createBondsBondBondSockets() {
        return new Bonds.Bond.BondSockets();
    }

    /**
     * Create an instance of {@link Bonds.Bond.BondPlugs }
     * 
     */
    public Bonds.Bond.BondPlugs createBondsBondBondPlugs() {
        return new Bonds.Bond.BondPlugs();
    }

    /**
     * Create an instance of {@link Plugs }
     * 
     */
    public Plugs createPlugs() {
        return new Plugs();
    }

    /**
     * Create an instance of {@link Sockets }
     * 
     */
    public Sockets createSockets() {
        return new Sockets();
    }

    /**
     * Create an instance of {@link OspModelDescription }
     * 
     */
    public OspModelDescription createOspModelDescription() {
        return new OspModelDescription();
    }

    /**
     * Create an instance of {@link Variables.Variable }
     * 
     */
    public Variables.Variable createVariablesVariable() {
        return new Variables.Variable();
    }

    /**
     * Create an instance of {@link Bonds.Bond.BondSockets.BondSocket }
     * 
     */
    public Bonds.Bond.BondSockets.BondSocket createBondsBondBondSocketsBondSocket() {
        return new Bonds.Bond.BondSockets.BondSocket();
    }

    /**
     * Create an instance of {@link Bonds.Bond.BondPlugs.BondPlug }
     * 
     */
    public Bonds.Bond.BondPlugs.BondPlug createBondsBondBondPlugsBondPlug() {
        return new Bonds.Bond.BondPlugs.BondPlug();
    }

    /**
     * Create an instance of {@link Plugs.Plug }
     * 
     */
    public Plugs.Plug createPlugsPlug() {
        return new Plugs.Plug();
    }

    /**
     * Create an instance of {@link Sockets.Socket }
     * 
     */
    public Sockets.Socket createSocketsSocket() {
        return new Sockets.Socket();
    }

}
