//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.26 at 06:53:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://open-simulation-platform.com/OspModelDescription/1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.opensimulationplatform.modeldescription.xml.model;
